### PR TITLE
Add --broker-auth into default docker container

### PR DESCRIPTION
**Pull request by nworbnhoj**
Authenticated subscription to HA Moscuitto broker is critical to stable message flow

### CODE REVIEW

**Comment by micolous** [comment]
Ah, it looks like #15 and #16 were supposed to be part of the same pull request.

**Comment by nworbnhoj** [comment]
Our Home Assistant - libcbus installation has been stable on Docker for 3+ months with these modifications.

**Comment by micolous** [comment]
This would bake those credentials into the Docker image, which isn't ideal.  Docker has a `secrets` system, but it looks like that only works with Swarms or Compose or something.

I've written something similar using [Docker volumes](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only) instead, which should achieve the same effect without needing to bake any sort of credentials in the image.  It will also adds some of the missing `cmqttd` options.

I'm writing up the docs for it now. :)

**Comment by micolous** [comment]
6a015fefbd74bb7b15be66b3c3abab8c6dd1dab5 should let you pass in authentication credentials using Docker volumes now.

Thanks!

**Pull request closed without merging**
